### ISSUE TITLE
[Suggestion] Use more letters in function clade_label

### ISSUE THREAD

**Issue by POPOP1** [yiluheihei/microbiomeMarker#10]
Hi yiluheihei,

It might be worth adding more letters in the function clade_label.

An example lists below:

```
LETTERS702 <- c(LETTERS, sapply(LETTERS, function(x) paste0(x, LETTERS)))

short_label <- LETTERS702[1:sum(ind)]
```

Output:

![image](https://user-images.githubusercontent.com/33267148/93621213-cf708c80-fa0d-11ea-87dd-562e3ed4735d.png)

Best,
Po

**Comment by yiluheihei** [comment]
Thanks for your suggestion. This feature is achieved in b08b24f
