### ISSUE TITLE
lefse_cladogram

### ISSUE THREAD

**Issue by lgralo** [yiluheihei/microbiomeMarker#11]
Hi,
I´m trying to get a cladogram by using the microbiomeMarker but I get this error:

lefse_cladogram(lefse_out, color = c("blue", "red"))
#Error in neworder[newpos] <- start : replacement has length zero

Could you help me to solve it?
Thank you!

**Comment by yiluheihei** [comment]
Sorry for the delayed response as I was on vacation. Could you please  provide a reproducible example. https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

**Comment by yiluheihei** [comment]
fixed in 46c6dd4. Please reinstall **microbiomeMarker** from github. 

Thanks for your feedback! If you think this project is helpful to you, you can give this project a star ⭐.
