### ISSUE TITLE
error in plot_cladogram function "TRUE/FALSE needed"

### ISSUE THREAD

**Issue by drelo** [yiluheihei/microbiomeMarker#113]
Dear all, 

I have a similar issue to #94 

After subsetting and running Lefse I would like to use the _**plot_cladogram**_ function. 

I used this code. 

```
smalltreatment <- phyloseq::subset_taxa(gp_filt, Phylum %in% c("Firmicutes"))
mm_lefse <- run_lefse(smalltreatment, wilcoxon_cutoff = 0.05,
group = "batch", taxa_rank = "Genus", kw_cutoff = 0.05, multigrp_strat = TRUE, lda_cutoff = 3)
plot_cladogram(mm_lefse, color = c("darkgreen", "red"))
```
I got the following error

`"Error in if (n <= length(x)) { : missing value where TRUE/FALSE needed"`

Could anyone help me to solve this issue, I am new to the phyloseq format but have performed lefse and graphlan before. 

Thanks

Andrés

**Comment by zhanxw** [comment]
You may want to put a minimal reproducible example. Otherwise, it is hard to tell what happened.
