### ISSUE TITLE
Error in lefse analysis

### ISSUE THREAD

**Issue by srisvs33** [yiluheihei/microbiomeMarker#12]
Hi,

I am getting the following error while doing lefse analysis. Any idea, what may the issue, and how to solve this.

**Error in split.default(subcls, cls) : 
  group length is 0 but data length > 0**

here is the code i have used

lefse_out <- lefse(physeq2, 
  normalization = 1e6, 
  class = "Genus",  multicls_strat = TRUE)
lefse_out

I have created a phyloseq object using import_mothur function in phyloseq. 

many thanks in advance
Venkat

**Comment by lixiaopi1985** [comment]
> Hi,
> 
> I am getting the following error while doing lefse analysis. Any idea, what may the issue, and how to solve this.
> 
> **Error in split.default(subcls, cls) : group length is 0 but data length > 0**
> 
> here is the code i have used
> 
> lefse_out <- lefse(physeq2,
> normalization = 1e6,
> class = "Genus", multicls_strat = TRUE)
> lefse_out
> 
> I have created a phyloseq object using import_mothur function in phyloseq.
> 
> many thanks in advance
> Venkat

The class is the metadata class (i.e. treatment), not taxonomy rankings. In your case, you specified Genus which can not be found in the metadata column, thus no group(group length=0)

**Comment by yiluheihei** [comment]
@srisvs33  As @lixiaopi1985 said,  the argument `class` should be a column name of the metadata.
