### ISSUE TITLE
Compatibility of DADA2 phyloseq object?

### ISSUE THREAD

**Issue by dikiprawisuda** [yiluheihei/microbiomeMarker#14]
Hi, I found an error like the following:
`Error in validObject(.Object) : invalid class “phyloseq” object: 
 Component taxa/OTU names do not match.
 Taxa indices are critical to analysis.
 Try taxa_names()`
I have tried to compare the spontaneous_colitis dataset with mine, with several accessor of [phyloseq](https://joey711.github.io/phyloseq/preprocess.html), and they are indeed different in quite so many ways. For starters `head(tax_table(spontaneous_colitis))` returning different format entirely from mine.
I wonder if this package compatible with phyloseq object that is derived from DADA2's seqtab.nochim and taxa table? What method was that used to generate spontaneous_colitis?

Thank you.
Best, 

PS: 
![carbon (1)](https://user-images.githubusercontent.com/55866525/95836157-0ec69a80-0d7a-11eb-873e-b24fa4d96cb5.png)
[Carbon URL](https://carbon.now.sh/?bg=rgba(58%2C63%2C70%2C1)&t=zenburn&wt=none&l=r&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=2x&wm=false&code=head(tax_table(data))%2520%2523%2523%2523%2523%250A%250ATaxonomy%2520Table%253A%2520%255B6%2520taxa%2520by%25207%2520taxonomic%2520ranks%255D%253A%250AKingdom%2520Phylum%2520Class%2520Order%2520Family%250AASV1%2520%2522Bacteria%2522%2520%2522Proteobacteria%2522%2520%2522Gammaproteobacteria%2522%2520%2522Enterobacteriales%2522%2520%2522Enterobacteriaceae%2522%250AASV2%2520%2522Bacteria%2522%2520%2522Actinobacteria%2522%2520%2522Actinobacteria%2522%2520%2522Bifidobacteriales%2522%2520%2522Bifidobacteriaceae%2522%250AASV3%2520%2522Bacteria%2522%2520%2522Firmicutes%2522%2520%2522Bacilli%2522%2520%2522Lactobacillales%2522%2520%2522Streptococcaceae%2522%250AASV4%2520%2522Bacteria%2522%2520%2522Actinobacteria%2522%2520%2522Actinobacteria%2522%2520%2522Bifidobacteriales%2522%2520%2522Bifidobacteriaceae%2522%250AASV5%2520%2522Bacteria%2522%2520%2522Firmicutes%2522%2520%2522Bacilli%2522%2520%2522Lactobacillales%2522%2520%2522Enterococcaceae%2522%250AASV6%2520%2522Bacteria%2522%2520%2522Actinobacteria%2522%2520%2522Actinobacteria%2522%2520%2522Bifidobacteriales%2522%2520%2522Bifidobacteriaceae%2522%250AGenus%2520Species%250AASV1%2520%2522Escherichia%252FShigella%2522%2520NA%250AASV2%2520%2522Bifidobacterium%2522%2520%2522longum%2522%250AASV3%2520%2522Streptococcus%2522%2520NA%250AASV4%2520%2522Bifidobacterium%2522%2520NA%250AASV5%2520%2522Enterococcus%2522%2520NA%250AASV6%2520%2522Bifidobacterium%2522%2520%2522bifidum%2522%250A%250A%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%2523%250A%250Ahead(tax_table(spontaneous_colitis))%2520%2523%2523%2523%2523%250A%250ATaxonomy%2520Table%253A%2520%2520%2520%2520%2520%255B6%2520taxa%2520by%25201%2520taxonomic%2520ranks%255D%253A%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520Summarize%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%250AArchaea%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2522Archaea%2522%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%250AArchaea%257CCrenarchaeota%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2522Archaea%257CCrenarchaeota%2522%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%250AArchaea%257CCrenarchaeota%257CThermoprotei%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2522Archaea%257CCrenarchaeota%257CThermoprotei%2522%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%250AArchaea%257CCrenarchaeota%257CThermoprotei%257CDesulfurococcales%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2522Archaea%257CCrenarchaeota%257CThermoprotei%257CDesulfurococcales%2522%2520%2520%2520%2520%2520%2520%2520%2520%2520%250AArchaea%257CCrenarchaeota%257CThermoprotei%257CSulfolobales%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2522Archaea%257CCrenarchaeota%257CThermoprotei%257CSulfolobales%2522%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%250AArchaea%257CCrenarchaeota%257CThermoprotei%257CSulfolobales%257CSulfolobaceae%2520%2522Archaea%257CCrenarchaeota%257CThermoprotei%257CSulfolobales%257CSulfolobaceae%2522)

**Comment by yiluheihei** [comment]
Thanks for your feedback. DADA2 phyloseq object is not suppoprted in the current version of **microbiomeMarker**. Can you provide your sample data of DADA2 and your code, so that I can add the feature to compatible with the output of DADA2.

**Comment by dikiprawisuda** [comment]
Hi! 
Thank you for your response. I hope it is okay to give you complete example instead of the reproducible one. The following data is exactly pasted from DADA2 web. The last section of lefse() function also gives an error I had.

Error in validObject(.Object) : invalid class “phyloseq” object: 
 Component taxa/OTU names do not match.
 Taxa indices are critical to analysis.
 Try taxa_names()



[DADA2sample.zip](https://github.com/yiluheihei/microbiomeMarker/files/5375522/DADA2sample.zip)

**Comment by yiluheihei** [comment]
Please reinstall microbioMarker and try again. For compatible with DADA2, I will add a function `import_dada2()` to import the ouput of dada2 as phyloseq object in the future.
