### ISSUE TITLE
DADA2 Phyloseq object to lefse

### ISSUE THREAD

**Issue by BPaarwater** [yiluheihei/microbiomeMarker#16]
Good day,

I hope all are well. I know you have addressed the issue before, however I am really keen to see how my data output will look using this package, as this will really help us understand our data much better, besides knowing the abundances, alpha and beta diversity. I know you mentioned that you will add the import_dada2() function soon. At what stage can we expect this?

**Comment by yiluheihei** [comment]
Please reinstall the package and test the new function `import_dada2()`.  

If you think this project is helpful to you, you can give this project a star :star:.
