### ISSUE TITLE
Can you make a tutorial starting from QIIME2 

### ISSUE THREAD

**Issue by yuyingxie** [yiluheihei/microbiomeMarker#17]
I am analyzing some 16S data using QIIME2 and used SILVA database to assigne taxonomy to the OTUs. However, there are many OTU only with taxonomy at the level of phylums or genus. For exmaple,

OTU1:  Bacteria|Actinobacteria|Actinobacteria|Coriobacteriales|Coriobacteriaceae|__
OTU2:  Bacteria\|Actinobacteria\|Actinobacteria\|Coriobacteriales\|Coriobacteriaceae\|Adlercreutzia
OTU3: Bacteria\|Actinobacteria\|Actinobacteria\|Coriobacteriales\|Coriobacteriaceae\|Asaccharobacter

What should I do for OTU1? 

Even for the example spontaneous_colitis in the tutorial, 
the OTU Bacteria|Actinobacteria|Actinobacteria|Coriobacteriales|Coriobacteriaceae
is not the sum of 

Bacteria\|Actinobacteria\|Actinobacteria\|Coriobacteriales\|Coriobacteriaceae\|Adlercreutzia
Bacteria\|Actinobacteria\|Actinobacteria\|Coriobacteriales\|Coriobacteriaceae\|Asaccharobacter
Bacteria\|Actinobacteria\|Actinobacteria\|Coriobacteriales\|Coriobacteriaceae\|Collinsella
Bacteria\|Actinobacteria\|Actinobacteria\|Coriobacteriales\|Coriobacteriaceae\|Coriobacterium
Bacteria\|Actinobacteria\|Actinobacteria\|Coriobacteriales\|Coriobacteriaceae\|Eggerthella
Bacteria\|Actinobacteria\|Actinobacteria\|Coriobacteriales\|Coriobacteriaceae\|Enterorhabdus
Bacteria\|Actinobacteria\|Actinobacteria\|Coriobacteriales\|Coriobacteriaceae\|Gordonibacter
Bacteria\|Actinobacteria\|Actinobacteria\|Coriobacteriales\|Coriobacteriaceae\|Olsenella
Bacteria\|Actinobacteria\|Actinobacteria\|Coriobacteriales\|Coriobacteriaceae\|Paraeggerthella
Bacteria\|Actinobacteria\|Actinobacteria\|Coriobacteriales\|Coriobacteriaceae\|Slackia

I am very confused.

Thanks so much for your help.

**Comment by yiluheihei** [comment]
The function `import_qiime2()` to import output of qiime2 into `phyloseq` object, and I have added a section `Data import` in the README to illustrate how to import external data files to phyloseq which can be used to downstream anaylis easily. Please reinstall this package and try this feature.  

Thanks for you suggestion. If you think this project is helpful to you, you can give this project a star :star:.
