### ISSUE TITLE
Package won't load for R v3.6.3

### ISSUE THREAD

**Issue by eag-microbio** [yiluheihei/microbiomeMarker#19]
Hello! 
I would love to try out this package. I've been stuggling with the https://github.com/biobakery/biobakery/wiki/lefse process and thought your package would be great.

I've tried downloading it, and this was the outcome "Error: Failed to install 'microbiomeMarker' from GitHub:
  (converted from warning) packages ‘edgeR’, ‘metagenomeSeq’, ‘ggtree’ are not available (for R version 3.6.3)" 

I wasn't sure if it is possible to update? 

Thanks for your time.

**Comment by yiluheihei** [comment]
Thanks for you question. edgeR, metagenomeSeq, ggtree are bioconductor packages. Please install this package use  function `install_github()` from package remotes, and the bioconductor packages will be installed automatically.

```
# use remotes::install_github()
remotes::install_github("yiluheihei/microbiomeMarker")
```

 If you think this project is helpful to you, you can give this project a star ⭐.
