### ISSUE TITLE
How to give a custom label for the lefse barplot in LDA analysis

### ISSUE THREAD

**Issue by lyjujose** [yiluheihei/microbiomeMarker#20]
Hi,

I am doing a LEfSe analysis of microbiome data. I have to add a custom label to the lefse barplot. As you can see in the attached figure, I need to replace the **Unknown** label with **sp.** label. Is there any other option to change the **Unknown** word in the **marker table** and plot the graph? 

Thank you very much for the wonderful tool.

![lefse_barplot_test3](https://user-images.githubusercontent.com/19813821/102936770-c7920f80-4476-11eb-8b62-fc910e68dce6.jpg)

**Comment by yiluheihei** [comment]
Please provide a minimal reproducible example
