### ISSUE TITLE
Lefse command work time

### ISSUE THREAD

**Issue by vca007** [yiluheihei/microbiomeMarker#22]
This is not an issue,but a question and I am not sure where to ask, so I apologize if it is not the right place. I was wondering how long for a normal computer would the lefse would need to process a phyloseq object. I launched a phyloseq object of 1400 OTUs, 7 taxonomic ranks and 12 samples on an evening and the next day it was still not finished. I am trying now with a subsample of the OTU table with 60 OTUs and it has been running for 1h. Just wanted to know if this was normal! Thank you!

**Comment by yiluheihei** [comment]
I think it is abnormal.

**Comment by vca007** [comment]
[Arch_14800_noedge_otus.txt](https://github.com/yiluheihei/microbiomeMarker/files/6083503/Arch_14800_noedge_otus.txt)
[sample_data_noedge.txt](https://github.com/yiluheihei/microbiomeMarker/files/6083504/sample_data_noedge.txt)
[Arch_14800_noedge_taxa.txt](https://github.com/yiluheihei/microbiomeMarker/files/6083505/Arch_14800_noedge_taxa.txt)

Hi I added here my files and below the script I use from creating phyloseq object to the function : 
`##Import OTU table
oarch_noedge <- read.delim("Arch_14800_noedge_otus.txt")
row.names(oarch_noedge) <- oarch_noedge$OTU
oarch_noedge=subset(oarch_noedge,select=-OTU)
oarch_noedge=as.matrix(oarch_noedge)
OTU_arch_noedge=otu_table(oarch_noedge,taxa_are_rows = TRUE)
##Import taxa table
tarch_noedge <- read.delim("Arch_14800_noedge_taxa.txt")
row.names(tarch_noedge) <- tarch_noedge$OTU
tarch_noedge =subset(tarch_noedge,select=-OTU)
tarch_noedge=as.matrix(tarch_noedge)
TAX_arch_noedge=tax_table(tarch_noedge)
##Import sample table
sample_noedge <- read.delim("sample_data_noedge.txt")
row.names(sample_noedge) <- sample_noedge$Sample
sample_noedge[,1]=NULL
sample_noedge$Habitat=as.factor(sample_noedge$Habitat)
sample_noedge$Habitat=as.factor(sample_noedge$General)
samples_noedge=sample_data(sample_noedge)

##Create phyloseq object and calculate CLR 
archbom_noedge=phyloseq(OTU_arch_noedge,TAX_arch_noedge,samples_noedge) #Resulting object is a formal class phyloseq
archbom_noedge_clr=microbiome::transform(archbom_noedge,"clr")

lefse_arch=lefse(archbom_noedge,norm="none",class="Habitat")`

Am I doing something wrong with either the input files or the command lines? Thanks!

**Comment by vca007** [comment]
Just to add infos, I was able to use the same phyloseq object with the command ldamarker from the package microbial. However I would very appreciate to be able to do it through this package for the cladogram function. Thanks again in advance for your thoughts on why it wouldnt be working!

**Comment by yiluheihei** [comment]
After a  deep test using your data, I think the reason for your error is the improper data input. The sample size for each group is too small, and the abudance profiles of some features maybe the [zero variance predictors](https://tgmstat.wordpress.com/tag/lda/),  which make the lda of these features cannot be calculated.
