### ISSUE TITLE
Negative LDA scores and order of bars

### ISSUE THREAD

**Issue by acmasche** [yiluheihei/microbiomeMarker#23]
Hi and thank you for the great package!

I have two questions:

1. It seems that since `lefse_barplot` was changed to `plot_ef_bar`, the bars are not ordered by class anymore. Is it possible to regain that feature?

What I get:
![image](https://user-images.githubusercontent.com/17832710/108200490-d6b3d780-711e-11eb-9ef9-6b87496f6eed.png)

What I would prefer:
![image](https://user-images.githubusercontent.com/17832710/108200627-006cfe80-711f-11eb-9d64-6a3d33678335.png)

  

2. `lefse` seems to produce only positive LDA scores, also for comparison of only two groups. I was wondering how this is related to the original LefSe by Segata et al. where there are positive and negative scores when two groups are compared. And as soon as >2 groups are compared there are only positive scores.  

Thanks in advance

**Comment by yiluheihei** [comment]
1. Thanks for your sugesstion. Could you please provide your output of `lefse()`, which can help me reproduce your plot and improve the `plot_ef_bar()` to make the bars ordered by class.

2.  According the original LefSe by Segata et al.,  the LDA score of `lefse` is the absolute value of original LDA.

**Comment by acmasche** [comment]
Thank you for your answer and sorry for the delay.
Here is the output of `lefse` which I get from your example data `spontaneous_coloitis`
[mm_spontaneous_colitis.RData.zip](https://github.com/yiluheihei/microbiomeMarker/files/6041795/mm_spontaneous_colitis.RData.zip)

And the code I used:

`library(microbiomeMarker);packageVersion("microbiomeMarker")`
[1] ‘0.0.1.9000’
`library(ggplot2)`

`data("spontaneous_colitis")`

`mm <- lefse(
spontaneous_colitis, 
norm = 1e6, 
class = "class", 
multicls_strat = TRUE
)`

`mm`

microbiomeMarker-class inherited from phyloseq-class
marker_table  Marker Table:      [ 29 microbiome markers with 5 variables ]
otu_table()   OTU Table:         [ 132 taxa and  30 samples ]
sample_data() Sample Data:       [ 30 samples by  1 sample variables ]
tax_table()   Taxonomy Table:    [ 132 taxa by 1 taxonomic ranks ]

`plot_ef_bar(mm)`
![image](https://user-images.githubusercontent.com/17832710/109130311-df756080-7751-11eb-88cc-52e65fcf6324.png)

**Comment by yiluheihei** [comment]
Fixed, please reinstall this package and try again.
