### ISSUE TITLE
  ranks of `ps` must be one of Kingdom, Phylum, Class, Order, Family, Genus, Species

### ISSUE THREAD

**Issue by rsiani** [yiluheihei/microbiomeMarker#24]
Hi,
I encountered this error and I don't know what is it referring to?

```
mm = lefse(physeq,
                  class = "Description",
                 subclass = "genotypes",
                 multicls_strat = T)
```
`Error in lefse(physeq, class = "Description", subclass = "genotypes",  : 
  ranks of `ps` must be one of Kingdom, Phylum, Class, Order, Family, Genus, Species`

**Comment by yiluheihei** [comment]
To make your problem easier to solve, please provide a minimal reproducible example. Or you can provide your `physeq` object so that I can reproduce your error.

see [here](https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) for how to make a great r reproducible example.

**Comment by rsiani** [comment]
By loading your example colitis physeq I figured out that you do not separate into taxonomic ranks (Domain, Phylum etc etc). So I have 7 ranks instead of just one.

**Comment by yiluheihei** [comment]
Sorry for the confusion casued by the example dataset `spontaneous_colitis`. The two datasets, `spontaneous_colitis` and `oxygen`,  are from the original python LefSe, which were not separated into taxonomic ranks.  These two not sepated dataset is just for test and will drop in the futhure.

However, other datasets, such as `cid_ying` have been separated into taxnomic ranks, and the data which has been separated is well supported in `microbiomeMarker::lefse`. The corresponding taxomic ranks must be named `Kingdom`, `Phylum`, `Class`, `Order`, `Family`, `Genus`, or `Species`.

**Comment by rsiani** [comment]
oh, I see. 
Than the problem could be that I have by default the Domain rank instead of Kingdom

**Comment by yiluheihei** [comment]
Glad that your problem is solved.
