### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by haolianxu** [yiluheihei/microbiomeMarker#27]
I had an issue in installing the package. it kept showing up even when I removed some packages. 

Error: Failed to install 'microbiomeMarker' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘S4Vectors’

**Comment by yiluheihei** [comment]
I think this problem is not caused by microbiomeMarker. 

Please try remove the package **S4Vectors** and reinstall microbiomeMarker.
