### ISSUE TITLE
Ancom  Error in `.rowNamesDF<-`(x, value = value) :    duplicate 'row.names' are not allowed

### ISSUE THREAD

**Issue by Hesham999666** [yiluheihei/microbiomeMarker#28]
Hi Guys 

So I am new to ANCOM analysis. when I am run.
mm_ancom <- run_ancom (airmicrobiome, "SampleType", p_adjust = "none", theta = 0.6)
I got the error  Error in `.rowNamesDF<-`(x, value = value) :    duplicate 'row.names' are not allowed.

Thanks 
Hesham

**Comment by yiluheihei** [comment]
Please provide a reproducible example, it will be much easier to solve your problem. https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example.

**Comment by Hesham999666** [comment]
Hi Yang 

How I can send you the  phyloseq object "airmicrobiome", Can you provide me with your email. it is around 7 MB I can not uploaded here.

**Comment by yiluheihei** [comment]
Please see the`Authors` field  in [DESCRIPTION file](https://github.com/yiluheihei/microbiomeMarker/blob/master/DESCRIPTION).

**Comment by yiluheihei** [comment]
Hi @Hesham999666, 

The reason for the error is that there is a sample (named `SRR6263071`) in which all otus are zero. This sample should be removed before differential analysis (e.g. ancom). And I have added a new step in the diffential analysis workflow to remove such samples ([41abf96](https://github.com/yiluheihei/microbiomeMarker/commit/41abf9640b61ab0de2ba56d1fa7fd3ee00a83673)).

However, ancom requires calculate pairwise log ratios between all features and performing a significance test to determine if there is a significant difference in feature ratios.  This means we need perform `p(p-1)/2` (`p` is the number of OTUs) significance test. However, there more than 24298 OTUs in your `phyloseq` object, and it will take a very long time to perform ancom differential analysis (may be several hours or days I guess).

As suggested in paper [Nature methods 10.1 (2013): 57-59.](https://doi.org/10.1038/nmeth.2276), "For datasets where a mock community is not included for calibration, we recommend the conservative threshold of (c = 0.005%). "  c is the OTU abundance threshold. Thus, I highly recommend to filter your OTUs with the threshold of 0.00005 before downstream analysis. Of note, lots of low abundance OTUs will be removed, and then the ancom differential analysis can be completed in less than 5 minites (on my mac pro 2014). The code are as follows:

```
ps <- readRDS("heshampig_bacteria_phyloseq.rds")
meta <- read.csv("metadata_exp.csv")
row.names(meta) <- meta$SampleID
sample_data(ps) <- sample_data(meta)

# remove low abundance otu, threshold is 0.005% (0.00005)
otu <- otu_table(ps)
high_otu_idx <- colSums(otu)/sum(otu) >= 0.00005
high_otu <- taxa_names(ps)[high_otu_idx]
ps2 <- prune_taxa(high_otu, ps)

res <- run_ancom (ps2, "SampleType", p_adjust = "none", theta = 0.6))
```



Please feel free to let me know if you have any further questions. If you think this project is helpful to you, you can give this project a star ⭐.
