### ISSUE TITLE
marker_table

### ISSUE THREAD

**Issue by provirasanz** [yiluheihei/microbiomeMarker#29]
Hello,

First of all, congratulations for the package. It works great! I only have one issue, which I am sure is very basic but I cannot realize how to handle it.  When I call the marker_table (mm), I get the  features list with numbers instead of the real taxa names. See example below. I appreciate your help.
Regards,

Pablo

head(marker_table(mm))

marker1            k__2|p__8|c__7|o__10|f__46|g__104        H-FEC 2.825221 0.02828012 0.02828012
marker2 k__2|p__8|c__7|o__10|f__46|g__104|s__104_s__        H-FEC 2.825221 0.02828012 0.02828012
marker3 k__2|p__8|c__7|o__10|f__46|g__105|s__105_s__        H-FEC 2.804623 0.03426606 0.03426606
marker4            k__2|p__8|c__7|o__10|f__46|g__105        H-FEC 2.804531 0.03426606 0.03426606
marker5                           k__2|p__8|c__8_c__        H-FEC 2.716615 0.04720177 0.04720177
marker6              k__2|p__8|c__8_c__|o__8_c___o__        H-FEC 2.716615 0.04720177 0.04720177

**Comment by yiluheihei** [comment]
Hi @provirasanz 

Thanks for your interest in microbiomeMarker.

Please provide a reproducibal example, so that your problem can be easily solved. You can attach your data and code under this issue.

Thanks.

**Comment by provirasanz** [comment]
Hi yiluheihei,

Thanks for you answer.
I generated the following phyloseq object based on the attached files (metadata, seqtab.nochim, otu_table, and taxa table) after following the dada2 tutorial Let me know any further question. Thanks again!

ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows=FALSE), 
               sample_data(metadata), 
               tax_table(taxa),phy_tree(fitGTR$tree))

# Rename ASVs to "ASV1, ASV2..."
dna <- Biostrings::DNAStringSet(taxa_names(ps))
names(dna) <- taxa_names(ps)
ps <- merge_phyloseq(ps, dna)
taxa_names(ps) <- paste0("ASV", seq(ntaxa(ps)))
ps

phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 2641 taxa and 10 samples ]
sample_data() Sample Data:       [ 10 samples by 4 sample variables ]
tax_table()   Taxonomy Table:    [ 2641 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 2641 tips and 2639 internal nodes ]

#metadata
[metadata.txt](https://github.com/yiluheihei/microbiomeMarker/files/6280249/metadata.txt)
#taxa table
[taxa.txt](https://github.com/yiluheihei/microbiomeMarker/files/6280255/taxa.txt)
#asv_table
[asv_table.xlsx](https://github.com/yiluheihei/microbiomeMarker/files/6280276/asv_table.xlsx)
#seqtab.nochim
[seqtab_nochim.txt](https://github.com/yiluheihei/microbiomeMarker/files/6280285/seqtab_nochim.txt)

**Comment by yiluheihei** [comment]
@provirasanz

Sorry for the delayed reply. You can serizlization you `ps` object using `saveRDS()`, and attach it under this isssue.

**Comment by provirasanz** [comment]
yiluheihei,

Thanks again for you answer and suggestions. As you required, I am attaching the phyloseq object (as a zip file because the system do not support the attachment of .rds files). I hope it helps.
Regards,

Pablo

[ezyzip.zip](https://github.com/yiluheihei/microbiomeMarker/files/6303876/ezyzip.zip)

**Comment by ytaoo** [comment]
Hi Pablo,

I had the same issue when I was first using this package, but I fixed it by updating my R to 4.0 and reinstalled this package. I think in my case it was because one of the depending packages does not work well with older versions of R. 

Hope this helps. 

Laura

**Comment by yiluheihei** [comment]
Hi @provirasanz 

Everything looks good after perfrom lefse analysis using your phyloseq input. 

As ytaoo said: it was because one of the depending packages does not work well with older versions of R. Please reinstall microbiomeMaker and update all the depences. 

please let me know if there is any further problem.

```
mm <- lefse(
  ps, 
  norm = 1e6, 
  class = "Fecal_Egg_Counts", 
  multicls_strat = TRUE
)

head(marker_table(mm))

                                      feature
marker1 k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Ruminiclostridium_6|s__Ruminiclostridium_6_s__
marker2                            k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Ruminiclostridium_6
marker3                            k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Ruminiclostridium_5
marker4 k__Bacteria|p__Firmicutes|c__Clostridia|o__Clostridiales|f__Ruminococcaceae|g__Ruminiclostridium_5|s__Ruminiclostridium_5_s__
marker5                                                                                   k__Bacteria|p__Firmicutes|c__Firmicutes_c__
marker6                                                             k__Bacteria|p__Firmicutes|c__Firmicutes_c__|o__Firmicutes_c___o__
        enrich_group      lda     pvalue       padj
marker1        H-FEC 2.862119 0.03426606 0.03426606
marker2        H-FEC 2.861894 0.03426606 0.03426606
marker3        H-FEC 2.814044 0.02828012 0.02828012
marker4        H-FEC 2.814044 0.02828012 0.02828012
marker5        H-FEC 2.685902 0.04720177 0.04720177
marker6        H-FEC 2.685902 0.04720177 0.04720177
```

**Comment by provirasanz** [comment]
yiluheihei and ytaoo,

Thank you very much for your time and comments. 
I will proceed with your suggestions and keep you uptated with the results.
Kind regards,

Pablo
