### ISSUE TITLE
Error in if (sum(class == cls) < sample_min)

### ISSUE THREAD

**Issue by xkcococo** [yiluheihei/microbiomeMarker#30]
Hi, I am trying to use this package to my data.
But I have an error when of lefse().

The  code I used is:
```
> ps
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 1939 taxa and 199 samples ]
sample_data() Sample Data:       [ 199 samples by 74 sample variables ]
tax_table()   Taxonomy Table:    [ 1939 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 1939 tips and 1938 internal nodes ]

> mm <- lefse(
+     ps,
+     norm = 1e6,
+     class = "breastfeeding_group",
+     multicls_strat = TRUE
+ )
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Found more than one class "phylo" in cache; using the first, from namespace 'phyloseq'
Also defined by ‘tidytree’
Error in if (sum(class == cls) < sample_min) { : 
  missing value where TRUE/FALSE needed
```

Could you help me to address it ? Thanks!

**Comment by yiluheihei** [comment]
Hi,

Thanks for your interest in this project. Please provide your input data (`phyloseq` object`) so that I can reproduce your problem.

**Comment by yiluheihei** [comment]
@xkcococo 

Has the problem been solved.

**Comment by Hiraik-Himura** [comment]
Hi,

Too much thanks for your amaizing work! 
I'm trying to run your code with my data set, but I don't know if I'm doing something wrong.

I have my data, imported to R with import_biom (Phyloseq), and have a tax_table by 7 tax ranks, so then generate the .txt with the same format hmp_small_aerobiosis.txt has. then I try to run lefse from your libary and i get an error 

Error in if (mean(x) && stats::sd(x)/mean(x) < 1e-10) { : 
  valor ausente donde TRUE/FALSE es necesario

I also tried to generate the file using the qiime2 tools, but i get the same error
My data set has 14 variables, so I only select one to generate the file, but nothing...

could you please give me a hint...

**Comment by yiluheihei** [comment]
@Hiraik-Himura To solve your problem, A reproducible example is appreciated.

**Comment by Hiraik-Himura** [comment]
@yiluheihei Hello, so much thanks for your answer!!! I apologize for been late, my mind runs whit an idea and another and another. But thanks to that I finally solve my problem. I´m not sure why, but my data couldn’t be processed until I aggregate sums for every taxa level, not only for the target level (Genus in my case). After that, the functions still not working, it said “an OTU_table is needed”. The error came from the function summarize_taxa, when the object out_summarized are constructed as data.frame, not as out_table. I add a line:
        otu_summarized<-otu_table(otu_summarized,taxa_are_rows = T)
and it worked. 
After that, it works lovely. 
I don't know if this problem is only happening to my data set. 
Too much tanks for your work!!! It helps me a lot!!!
