### ISSUE TITLE
object  not found

### ISSUE THREAD

**Issue by akhst7** [yiluheihei/microbiomeMarker#31]
Hi, 

I run a following line;

`test.a<-test_multiple_groups(m192, group = "Type", method = "anova", p_adjust = "fdr" )`

and got this error;

`object 'k__Bacteria___p__Proteobacteria___c__Gammaproteobacteria___o__Enterobacteriales___f__Enterobacteriaceae___g__Escherichia___Shigella___s__Escherichia.coli.O157' not found`

However it is in the taxa table:

```
>tax_table(m192)[1996]
Taxonomy Table:     [1 taxa by 7 taxonomic ranks]:
        Kingdom    Phylum           Class                 Order               Family               Genus                  Species                   
OTU1578 "Bacteria" "Proteobacteria" "Gammaproteobacteria" "Enterobacteriales" "Enterobacteriaceae" "Escherichia-Shigella" "Escherichia.coli.O157:H7"
```

and the OTU table;

```
>otu_table(m192)[1996,]
OTU Table:          [1 taxa and 24 samples]
                     taxa are rows
        UAB.3 UAB.4 UAB.5 UAB.6 UAB.7 UAB.8 UAB.11 UAB.12 UAB.13 UAB.14 UAB.15 UAB.16 UAB.19 UAB.20 UAB.21 UAB.22 UAB.23 UAB.24 UAB.27 UAB.28 UAB.29 UAB.30 UAB.31 UAB.32
OTU1578     2     4    13    28    21     1      0      2      1     19      4      0      5      8      0      0      1      0      1      0      0      0      0      0
```
Is the presence  of ":" in the taxa name the issue ? 

The phyloseq file in question can be downloaded from  

[https://microbimemarker.s3.us-east-2.amazonaws.com/mm.RDS](url)

Thanks.

**Comment by yiluheihei** [comment]
@akhst7  Thanks for your interest in microbiomeMarker. Sorry for the delayed response. I will try to solve your problem ASAP.

**Comment by akhst7** [comment]
solved.

**Comment by yiluheihei** [comment]
Could you share the solution to your problem under this issue so that other users can find it.  Thanks.
