### ISSUE TITLE
Installation R

### ISSUE THREAD

**Issue by yg-gy** [yiluheihei/microbiomeMarker#34]
Error: .onload failed in loadNamespace() for 'Cairo'
Reason: image not found
ERROR: lazy loading failed for package 'microbiomeMarker'

I am running R version 4.0.5 on a Mac. 

Any clues?

**Comment by yiluheihei** [comment]
I think it is a issue with Cairo rather than microbiomeMarker.

**Comment by Luponsky** [comment]
Hi, I just solved this problem in linux (maybe it could be useful) doing that:
from linux terminal:
sudo apt-get install libcairo2-dev
sudo apt-get install libxt-dev

from R studio
install.packages('Cairo')
BiocManager::install("ComplexHeatmap")
remotes::install_github("yiluheihei/microbiomeMarker")

**Comment by yiluheihei** [comment]
Glad to hear that your problem is resolved.
