### ISSUE TITLE
Cladogram error

### ISSUE THREAD

**Issue by mnhuda** [yiluheihei/microbiomeMarker#35]
Hello  @yiluheihei,

This is a nice tool for R users. The LDA plots look great. However, I got the following error message when I start making the cladogram.  

_Error in if (n <= length(x)) { : missing value where TRUE/FALSE needed_

I would appreciate any suggestion to overcome this issue. Please let me know if you have any questions. 

Regards,
Nazmul

LDA plot is here:
![G CSFLDA_Plot](https://user-images.githubusercontent.com/19982137/118324434-e55c2180-b4b6-11eb-9da8-0808fb9c8f89.jpeg)

**Comment by yiluheihei** [comment]
@mnhuda  Thanks for your interest in microbiomeMarker.

Please provide a reproducible example, it will be much easier to solve your problem.

**Comment by mnhuda** [comment]
@yiluheihei, after updating all the dependent packages, it has started working without any issue. Thank you so much for developing the package.
