### ISSUE TITLE
MicrobiomeMarker analysis for a specific taxonomic rank

### ISSUE THREAD

**Issue by CRichard21** [yiluheihei/microbiomeMarker#37]
Hello @yiluheihei 

First, I would like to thank you for this amazing job. I think you will facilitate the job of a lot of biostatistician.

I saw that all your analyses, as DESeq, were run on all taxonomic levels thanks to your function "summarize_taxa". However, I'm often interested in the most specific taxanomic rank "Species", but that's the level that will often determine the metabolic function. I do not necessarly want to over-correct the p-value for unwanted tests.

Is there any way I can ignore this behavior ? As an option in the main function run_* or by modifying my phyloseq object before running it ?

Best,

Corentin

**Comment by yiluheihei** [comment]
@CRichard21 Thanks for your interest in microbiomeMarker. I'm very sorry for the delayed reply.

Unfortunately, it is not allowed to analysis for a specific taxonomic rank in the current version. May be a extra para `summarize = TRUE/FALSE` can be added to control whether summarize the phyloseq object.

Should you have any further suggestions, please do not hesitate to contact me. 

Thanks.
