### ISSUE TITLE
DOI

### ISSUE THREAD

**Issue by akhst7** [yiluheihei/microbiomeMarker#38]
HI, 

DOI in the citation does match with any DOI online remote libraries including Pubmed, and Crossref.  Which remote library does this DOI point to ?   

Thanks.

**Comment by yiluheihei** [comment]
@akhst7 Thanks for your interested in microbiomeMarker.

microbiomeMarker is currently under development. We will write an academic paper on microbiomeMarker after the development is completed (maybe in the second half of this year).  All feedback and comments are very welcome.

The DOI in the citation (DOI: 10.5281/zenodo.3749415) is point to Zenodo, a general-purpose open-access repository which allows researchers to deposit research papers, data sets, research software, reports, and any other research related digital artifacts.

Hope this helps.
