### ISSUE TITLE
norm options for lefse

### ISSUE THREAD

**Issue by acmasche** [yiluheihei/microbiomeMarker#39]
Hi and thank you again for the great package.

I am having trouble getting `norm` options other than the default to work in `lefse`.

For example: 
`data("spontaneous_colitis")`
`lefse(
    spontaneous_colitis, 
    class = "class", 
   multicls_strat = TRUE
  )`

Runs as expected resulting in: 

microbiomeMarker-class inherited from phyloseq-class
marker_table  Marker Table:      [ 29 microbiome markers with 5 variables ]
otu_table()   OTU Table:         [ 132 taxa and  30 samples ]
sample_data() Sample Data:       [ 30 samples by  1 sample variables ]
tax_table()   Taxonomy Table:    [ 132 taxa by 1 taxonomic ranks ]

However, with e.g. total sum scaling it does not work: 
`lefse(
    spontaneous_colitis, 
    norm="TSS",
    class = "class", 
   multicls_strat = TRUE
  )`

Error: `norm` must be a numeric or "none" while `ps` has been summarized

This error occurs for all `norm`options including `"none"`.

I updated the package yesterday: 
`packageVersion("microbiomeMarker")`
‘0.0.1.9000’

Thanks in advance for your help.

**Comment by yiluheihei** [comment]
@acmasche I'm very sorry for the delayed response. The `spontaneous_colitis` is a sample data from the original python lefse script, which has been summarized. For the summarized data, only CPM normalization was supported.  This sample data only used for test to ensure the result of `run_lefse` in microbiomeMarker is inconsistent with the original lefse script. 

For the general phyloseq object of which the taxa was not summarized, all the normalization methods has been supported.

Thanks for your interested in microbiomeMarker, any further feedback is appreciated.
