### ISSUE TITLE
Error in read.table

### ISSUE THREAD

**Issue by Jalalalzanin** [yiluheihei/microbiomeMarker#43]
Hi everyone
I'm using "microbiomeMarker" for LEfSe analysis 
following the importing data from Qiime instructions:
otuqza_file <- system.file("extdata", "table.qza", package = "microbiomeMarker")
taxaqza_file <- system.file("extdata", "taxonomy.qza", package = "microbiomeMarker")
sample_file <- system.file("extdata", "metadata.tsv", package = "microbiomeMarker")
treeqza_file <- system.file("extdata", "tree.qza", package = "microbiomeMarker")

I got an error after running:
ps <- import_qiime2(
  otu_qza = otuqza_file, taxa_qza = taxaqza_file,
  sam_tab = sample_file, tree_qza = treeqza_file)
 
Error in read.table(file = mapfilename, header = TRUE, sep = "\t", comment.char = "") : 
  no lines available in input
In addition: Warning message:
In file(file, "rt") :
  file("") only supports open = "w+" and open = "w+b": using the former

all the input files are working well with me in qiime2

any help is appreciated
thank you

**Comment by yiluheihei** [comment]
@Jalalalzanin I'm very sorry for the delay response. Does your problem solved?  If not, please intall the latest version and try again. Thanks.

**Comment by Jalalalzanin** [comment]
Hi @yiluheihei 
Not yet. that's good, I will try it later this week and let you know if the problem is solved by the new version or not.
Thank you.
