### ISSUE TITLE
cladogram

### ISSUE THREAD

**Issue by Luponsky** [yiluheihei/microbiomeMarker#49]
Dear Yang Cao,
I thanks you for the incredible package that you developed!

I would like to slightly modify the cladogram produced with the function plot_cladogram:

I would like to remove the white nodes, which they should not be significant to the plot, and to increase the label size of the clades into the cladogram ( i.e., the alphabet letters)
I hope you can help me,
Cheers
L

**Comment by yiluheihei** [comment]
@Luponsky  Thanks for your interested in microbiomeMarker. 

Maybe I can add a extra parameter (e.g. `significant`) to specify whether only show the significant features (`TRUE`) or show all the features in the plot (`FALSE`). What do you think?

**Comment by Luponsky** [comment]
Dear @yiluheihei ,it  would be fantastic, I think it will be useful to every user to have such parameter!
Could you also add the parameter to increase the alphabet letter in the cladogram?

Thanks for the support,
L

**Comment by yiluheihei** [comment]
@Luponsky I have added a para `only_marker` in the `plot_cladogram()`, please install the dev version from github and try it. Feel free contact me if there is any problem.

**Comment by Luponsky** [comment]
@yiluheihei Thank you so much, It is working perfectly. 
I still don't succeed to increase the size of the  alphabet letters in the cladogram :( I tried to modify the function plot_cladogram without results. what it could be the correct approach??

**Comment by yiluheihei** [comment]
Currently, the size of alphabet letters in the cladogram are fixed, maybe it requires a extra parameter to set the font size of it.

**Comment by Luponsky** [comment]
Okay, 
Thank you so much for the help!
L

**Comment by yiluheihei** [comment]
A new argument `clade_label_font_size` was added to specify the font size of clade label of cladogram. You can reinstall it from github and try again.

**Comment by Luponsky** [comment]
Hello, sorry for the late answer, it works perfectly,
thank you so much!
cheers,
L
