### ISSUE TITLE
error:ranks of ps must be one of Kingdom, Phylum, Class, Order, Family, Genus, Species

### ISSUE THREAD

**Issue by SNOWBRO123** [yiluheihei/microbiomeMarker#51]
Hi,
I encountered this error
```
> tg_welch <- run_test_two_groups(
+   physeq_test,
+   group = "ypCR",
+   method = "welch.test"
+ )
Error in run_test_two_groups(physeq_test, group = "ypCR", method = "welch.test") : 
  ranks of `ps` must be one of Kingdom, Phylum, Class, Order, Family, Genus, Species
```
Then I check the rank names of  "physeq_test"
```
> rank_names(physeq_test)         
[1] "Kindom"  "Phylum"  "Class"   "Order"   "Family" 
[6] "Genus"   "Species"
```
I don't know why this error happen?
There is  my physeq object. Can you help me to check how this error happen
[physeq_test.zip](https://github.com/yiluheihei/microbiomeMarker/files/7586692/physeq_test.zip)

**Comment by yiluheihei** [comment]
@SNOWBRO123  Thanks for your interested in microbiomeMarker. 

Please correct the `Kindom` to `Kingdom` in your data and try again.

**Comment by SNOWBRO123** [comment]
OH, I didn't notice the spelling mistake.Thank you!
