### ISSUE TITLE
Error in validObject(.Object) : invalid class “phyloseq” object:

### ISSUE THREAD

**Issue by akhst7** [yiluheihei/microbiomeMarker#54]
I have this filtered phyloseq obj;

```
> m163.fil
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 364 taxa and 24 samples ]
sample_data() Sample Data:       [ 24 samples by 1 sample variables ]
tax_table()   Taxonomy Table:    [ 364 taxa by 7 taxonomic ranks ]
```
I run norm_cpm then I got this error;

```
Error in validObject(.Object) : invalid class “phyloseq” object: 
 Component taxa/OTU names do not match.
 Taxa indices are critical to analysis.
 Try taxa_names()
```
I checked and made sure that taxa name and OUT taxa name matched;

```
setdiff(unique(taxa_names(m163.fil)), unique(colnames(otu_table(m163.fil))))
character(0)

setdiff(taxa_names(m163.fil), colnames(otu_table(m163.fil)))
character(0)
```

So what am I missing ?

**Comment by akhst7** [comment]
I figured this out.

**Comment by yiluheihei** [comment]
@akhst7 Great. Thanks for your interested in microbiomeMarker. Could you share what the problem is and how you fixed it to help others learn from it?

Thanks.

**Comment by akhst7** [comment]
@yiluheihei,  microbiomeMakar requires the taxa(OTU or ASV) to be in the row not in the column.  If the  ASV table is generated by Dada2, phyloseq importing needs `taxa_are_rows=FALSE`, which basically puts the taxa in the column of the OTU table.  To fix this issue is to simply transpose axis as follows;

`otu_table(obj)<-t(otu_table(obj)`

**Comment by yiluheihei** [comment]
Many thanks for your feedback!
