### ISSUE TITLE
Hello. A Warning message is observed when 'run_lefse' is executed with microbiomeMarker.

### ISSUE THREAD

**Issue by holyknight760** [yiluheihei/microbiomeMarker#58]
Warning message:
No markers were identified

As the above message is generated, NULL is created in marker_table. How do we solve this problem?

**Comment by yiluheihei** [comment]
Thanks for your interested in microbiomeMarker. Maybe you can set a loose value for `lda_cutoff`, `kw_cutoff` `wilcoxon.cutoff` and `strict`.
