### ISSUE TITLE
more than one taxa_rank but not "all" option?

### ISSUE THREAD

**Issue by marwa38** [yiluheihei/microbiomeMarker#67]
Thanks very much for microbiomeMarker, it is so helpful on different levels. 
Could you please let me know if you can add an option to do both "Phylum" and "Genus" at the same time? so it is not "all" taxa but only 2 ranks? so that we can see to which Phylum a genus belongs to in the same figure?

something like the following?
```
# phylum + genus 
lefse.phyGen <- run_lefse(ps.prev, group = "treatment", taxa_rank = c("Phylum","Genus"), norm = "CPM", multigrp_strat = TRUE)
```

in case of `taxa_rank = c("all")`, can I have the taxa arranged so that I know which Genus belongs to Phylum and all other levels?
![image](https://user-images.githubusercontent.com/68851733/160235205-3c63e2ee-97b1-453e-ab35-e792430abf53.png)

Many thanks 
M

**Comment by yiluheihei** [comment]
@marwa38 Sorry for the late reply.  For the bar or dot plot, to make the figure look better (the full name of the marker could be too long), a argument `max_label_len` was provided to specify the maximum number of characters of the marker label (default 60).  To find which Phylum a genus belongs to,  you can see the full name of the feature in the `marker_table` slot of the result, and cladogram is recommended which can show the markers at each phyphylogenetic level.

Thanks for you feedback. Hope this helps to you.
