### ISSUE TITLE
A way to select description for trait

### ISSUE THREAD

**Issue by aarondeming** [yiluheihei/microbiomeMarker#69]

**Comment by aarondeming** [comment]
Hello! I was wondering if I could/ another method to select a different trait for import_picrust2 function besides the given 6 for example select the output for description? 

`import_picrust2(feature_tab, 
                          sam_tab,
                          trait = c("PATHWAY"))`

**Comment by yiluheihei** [comment]
Thanks for your interested in microbiomeMarker. As shown in the help page, seven options"PATHWAY", "COG", "EC", "KO", "PFAM", "TIGRFAM", "PHENO" are supported for `import_picrust2()`.
