### ISSUE TITLE
Error in lda_means[x, ] : subscript out of bounds

### ISSUE THREAD

**Issue by svenyos** [yiluheihei/microbiomeMarker#7]
I'm encountering an error **lda_means[x, ] : subscript out of bounds** with certain - but not all - subsetted Phyloseq objects when I run lefse (with default arguments), as follows
```
lefse_As <- microbiomeMarker::lefse(AlvPhylo_HxO.As, class = "organ")
```
Where AlvPhylo_HxO.As is the subsetted PS object and "organ" is the grouping factor (ie class). The problem does not arise if I use the full ps dataset and curiously on the AlvPhylo_HxO.As subsetted dataset, the script works when I select an alternative grouping factor.

A quick search online suggests the problem _may_ be here:

```
purrr::map(pair, function(x) {
    if (x %in% lda_row_nms) {
        lda_means[x, ]
    }
    else {
        rep(0, feature_n)
    }
```
WHich is the last entry in the textdump

Do you have any suggestions on where to start?

**Comment by yiluheihei** [comment]
If you provide a reproducible example, it will be much easier to solve the problem.
https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

**Comment by svenyos** [comment]
I've emailed you with the Rdata to accompany this

```
setwd(choose.dir())

#install and load packages
if (!requireNamespace("remotes", quietly = TRUE)) 
  install.packages("remotes")

if (!requireNamespace("microbiomeMarker", quietly = TRUE))
remotes::install_github("yiluheihei/microbiomeMarker")

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

if (!requireNamespace("phyloseq", quietly = TRUE))
  BiocManager::install("phyloseq")

if (!requireNamespace("tidyverse", quietly = TRUE))
install.packages("tidyverse")


library(tidyverse)
library(phyloseq)
library(microbiomeMarker)

```
**full data set is "PS_HxO.CSS" (can be found in Rdata in zip file):**
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 249 taxa and 80 samples ]
sample_data() Sample Data:       [ 80 samples by 9 sample variables ]
tax_table()   Taxonomy Table:    [ 249 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 249 tips and 248 internal nodes ]

I subset this dataset using phyloseq's subset_sample() function

```
#subset PS by "host" species
PS_HxO.Ak<- subset_samples(PS_HxO.CSS, host=="Ak")
PS_HxO.As<- subset_samples(PS_HxO.CSS, host=="As")
PS_HxO.Ab<- subset_samples(PS_HxO.CSS, host=="Ab")
```

The lefse() function works fine on the full dataset
```
#create lefse object with Full dataset
    # with lefse Class = organ
    lefseOUT.organ <- microbiomeMarker::lefse(PS_HxO.CSS, class = "organ")
    #plot bar
    PLOTlefse.organ <- lefse_barplot(lefseOUT.organ, label_level = 1, max_label_len = 100) + scale_fill_manual(values = 
    c("#ffa6a0","#ffdd94","#3699db","#cd85e5"))
    PLOTlefse.organ

    # with lefse Class = host
    lefseOUT.host <- microbiomeMarker::lefse(PS_HxO.CSS, class = "host")
    #plot bar
    PLOTlefse.host <- lefse_barplot(lefseOUT.host, label_level = 1, max_label_len = 100) + scale_fill_manual(values = 
    c("#00b448","#892ca0","#d40000"))
    PLOTlefse.host

```


However, the lefse() function only works sporadically in subsetted PS objects

e.g.
Host Ak dataset (48 of 80 samples) appears to run fine
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 249 taxa and 48 samples ]
sample_data() Sample Data:       [ 48 samples by 9 sample variables ]
tax_table()   Taxonomy Table:    [ 249 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 249 tips and 248 internal nodes ]

```
#first create a textdump file for comparative purposes: problematic subsetted PS objects are for host As and host Ab (last two)
options(error = quote(dump.frames("testdumpAk", TRUE))) 

#Run lefse function on PS_HxO.Ak <---- this subsetted PS object appears to run fine
lefseOUT_Ak <- microbiomeMarker::lefse(PS_HxO.Ak, class = "organ", lda_cutoff = 2)
#plot bar
PLOTlefseAk <- lefse_barplot(lefseOUT_Ak, label_level = 1, max_label_len = 100) + scale_fill_manual(values = c("#ffa6a0","#ffdd94","#3699db","#cd85e5"))
PLOTlefseAk
```
NB using lefse class = "site" also works for this subsetted dataset 





However, problems occur in the other two smaller subsetted datasets (fewer samples in both)
e.g.
Host As dataset (20 of 80 samples) <----------------- NB around half the number of Ak samples
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 249 taxa and 20 samples ]
sample_data() Sample Data:       [ 20 samples by 9 sample variables ]
tax_table()   Taxonomy Table:    [ 249 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 249 tips and 248 internal nodes ]
```
#first create a textdump file for comparative purposes
options(error = quote(dump.frames("testdumpAs_organ", TRUE))) 

#Run lefse function on PS_HxO.As (class = organ)  <---- This subsetted PS object encounters "lda_means[x, ] : subscript out of bounds" error, when Class = host
lefseOUT_As.organ <- microbiomeMarker::lefse(PS_HxO.As, class = "organ", lda_cutoff = 2)
#plot bar
PLOTlefseAs.organ <- lefse_barplot(lefseOUT_As.organ, label_level = 1, max_label_len = 100) + scale_fill_manual(values = c("#ffa6a0","#ffdd94","#3699db","#cd85e5"))
PLOTlefseAs.organ
```
BUT... running lefse function on the same dataset works when an alternative grouping variable is used, e.g. "site"

```
#first create a textdump file for comparative purposes
options(error = quote(dump.frames("testdumpAs_site", TRUE)))

#Running lefse function on the same dataset with Class = site
lefseOUT_As.site <- microbiomeMarker::lefse(PS_HxO.As, class = "site", lda_cutoff = 2)
#plot bar
PLOTlefseAs.site <- lefse_barplot(lefseOUT_As.site, label_level = 1, max_label_len = 100) + scale_fill_manual(values = c("#011f4b","#005b96","#b3cde0"))
PLOTlefseAs.site
```


and finally the smallest subsetted dataset
Host Ab dataset (12 of 80 samples) <----------------- NB quarter the number of Ak samples 
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 249 taxa and 12 samples ]
sample_data() Sample Data:       [ 12 samples by 9 sample variables ]
tax_table()   Taxonomy Table:    [ 249 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 249 tips and 248 internal nodes ]

```
#first create a textdump file for comparative purposes
options(error = quote(dump.frames("testdumpAb", TRUE)))

#Run lefse function on PS_HxO.Ab (class = organ) <---- This subsetted PS object encounters "lda_means[x, ] : subscript out of bounds" error

lefseOUT_Ab <- microbiomeMarker::lefse(PS_HxO.Ab, class = "organ", lda_cutoff = 2)
#plot bar
PLOTlefseAb <- lefse_barplot(lefseOUT_Ab, label_level = 1, max_label_len = 100) + scale_fill_manual(values = c("#ffa6a0","#ffdd94","#3699db","#cd85e5"))
PLOTlefseAb
#NB Host Ab only occurs at one sample site, so an equivalent check with "site" cannot be performed
```

**Comment by yiluheihei** [comment]
I have fixed this issue. Please reinstall the package from github and test your code. If you think this project is helpful to you, you can give this project a star ⭐. Thanks for your feedback!

**Comment by svenyos** [comment]
That's great, thanks!
