### ISSUE TITLE
contrast for multiple groups (edgeR)

### ISSUE THREAD

**Issue by ignadb** [yiluheihei/microbiomeMarker#70]
Hi Yang, 

Thanks so much for developing microbiome marker. It is very useful!

Now I am using it to analyse my data, which has 4 groups. I would like to use edgeR for the analysis. I however got some questions concerning contrast. In the manual of microbiome marker (under details toward the end of page 45), it says .. "_**users do required to concern this parameter (set as default NULL), and if there are two groups, the first level of groups will set as the reference group; if there are multiple groups, it will perform an ANOVA-like testing to find markers which difference in any of the groups**_".

In my case, I have multiple groups and I would like to perform an ANOVA-like testing. Shall I leave it as default (NULL)? Or should I set it something else? Thanks a lot and looking forward to hearing from you.

Best regards,
Chatchai

**Comment by yiluheihei** [comment]
Hi @ignadb  Thanks for your interested in microbiomeMaker. To perform an ANOVA-like tesing, you can leave `contrast` as the default `NULL`
