### ISSUE TITLE
Why same LEfSe object gives different taxa in Cladogram and LDA BarPlot?

### ISSUE THREAD

**Issue by borexino** [yiluheihei/microbiomeMarker#71]
I'm newbie in microbiome and I think that microbiomeMarker is a good package to start learing.
I've this example which produce these plot:

```
library(microbiomeMarker)
library(phyloseq)
library(ggplot2)

data(kostic_crc)
kostic_crc_small <- phyloseq::subset_taxa(
                                    kostic_crc,
                                    Phylum %in% c("Firmicutes"))
# Run LEfSe
mm_lefse <- run_lefse(
                kostic_crc_small,
                wilcoxon_cutoff = 0.01,
                group = "DIAGNOSIS",
                kw_cutoff = 0.01,
                multigrp_strat = TRUE,
                lda_cutoff = 4)
# Plot clado
plot_cladogram(mm_lefse, color = c("darkgreen", "red"))

# Defining enriched group
mm_lefse@marker_table$ef_lda <- ifelse(mm_lefse@marker_table$enrich_group == "Healthy", -mm_lefse@marker_table$ef_lda, mm_lefse@marker_table$ef_lda)

# Plot LEfSe
plot_ef_bar(mm_lefse) + scale_fill_manual(values = c("darkgreen", "red"))
```
### Plots:
<img width="652" alt="Clado" src="https://user-images.githubusercontent.com/7254017/164021494-fe52f113-777d-45d0-ae0a-b74db75b1682.png">

My question is why I've different taxa results? What a I missed?

**Comment by yiluheihei** [comment]
@borexino Sorry for the delayed reply.  For the cladogram, there is a argument `clade_label_level` (default 4 ) to specify the max level of taxa used to label the clade, and other level of taxa will be shown on the side. By default `clade_label_level  = 4`, this means that markers whose level than 4 (order) are showed in the clade. And in your example four markers including c__Clostridia, o__Clostridiales, c__Bacilli, and o__Lactobacillales are shown in the clade, and the other eight are shown on the side. And for the bar plot, all the 12 markers are shown, so there is no different taxa in cladogram and bar plot.

Hope this helps.
