### ISSUE TITLE
issues installing from bioconductor

### ISSUE THREAD

**Issue by mawa86** [yiluheihei/microbiomeMarker#77]
R (4.2.0) cannot get a hold of gsl-config, therefore both gsl and RcppGSL fail to compile, and, in succession, all the other dependencies. 

I don't know how to better explain it, so I'll just post the console messages when trying to install from BiocManager:

```
 if (!require("BiocManager", quietly = TRUE))
   install.packages("BiocManager")
 BiocManager::install("microbiomeMarker")
```

>'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

>replacement repositories:
    CRAN: https://cloud.r-project.org

>Bioconductor version 3.15 (BiocManager 1.30.18), R 4.2.0 (2022-04-22)
Installing package(s) 'microbiomeMarker'
also installing the dependencies ‘RcppGSL’, ‘gsl’, ‘RcppZiggurat’, ‘energy’, ‘Rfast’, ‘ANCOMBC’, ‘ALDEx2’

#### **Goes and downloads ‘RcppGSL_0.3.11’, ‘gsl_2.1-7.1’, ‘RcppZiggurat_0.1.6’, ‘energy_1.7-10’, ‘Rfast_2.0.6’, ‘ANCOMBC_1.6.2’, ‘ALDEx2_1.28.1’ and 'microbiomeMarker_1.2.2' tarballs successfully from both CRAN and Bioconductor**

>* installing *source* package ‘RcppGSL’ ...
** package ‘RcppGSL’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for gsl-config... no
configure: error: gsl-config not found, is GSL installed?
ERROR: configuration failed for package ‘RcppGSL’
>* removing ‘/home/myPCname/R/x86_64-pc-linux-gnu-library/4.2/RcppGSL’
>* installing *source* package ‘gsl’ ...
** package ‘gsl’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gsl-config... no
configure: error: gsl-config not found, is GSL installed?
ERROR: configuration failed for package ‘gsl’

**First two ERROR messages are for gsl-config not found**

>* removing ‘/home/myPCname/R/x86_64-pc-linux-gnu-library/4.2/gsl’
ERROR: dependency ‘RcppGSL’ is not available for package ‘RcppZiggurat’
>* removing ‘/home/myPCname/R/x86_64-pc-linux-gnu-library/4.2/RcppZiggurat’
ERROR: dependency ‘gsl’ is not available for package ‘energy’
>* removing ‘/home/myPCname/R/x86_64-pc-linux-gnu-library/4.2/energy’
ERROR: dependency ‘RcppZiggurat’ is not available for package ‘Rfast’
>* removing ‘/home/myPCname/R/x86_64-pc-linux-gnu-library/4.2/Rfast’
ERROR: dependency ‘energy’ is not available for package ‘ANCOMBC’
>* removing ‘/home/myPCname/R/x86_64-pc-linux-gnu-library/4.2/ANCOMBC’
ERROR: dependency ‘Rfast’ is not available for package ‘ALDEx2’
>* removing ‘/home/myPCname/R/x86_64-pc-linux-gnu-library/4.2/ALDEx2’
ERROR: dependencies ‘ANCOMBC’, ‘ALDEx2’ are not available for package ‘microbiomeMarker’
>* removing ‘/home/myPCname/R/x86_64-pc-linux-gnu-library/4.2/microbiomeMarker’

>The downloaded source packages are in
	‘/tmp/RtmpBPvUiK/downloaded_packages’
>Installation paths not writeable, unable to update packages
  path: /usr/lib/R/library
  packages:
    nlme, spatial, survival
>Warning messages:
1: In install.packages(...) :
  installation of package ‘RcppGSL’ had non-zero exit status
2: In install.packages(...) :
  installation of package ‘gsl’ had non-zero exit status
3: In install.packages(...) :
  installation of package ‘RcppZiggurat’ had non-zero exit status
4: In install.packages(...) :
  installation of package ‘energy’ had non-zero exit status
5: In install.packages(...) :
  installation of package ‘Rfast’ had non-zero exit status
6: In install.packages(...) :
  installation of package ‘ANCOMBC’ had non-zero exit status
7: In install.packages(...) :
  installation of package ‘ALDEx2’ had non-zero exit status
8: In install.packages(...) :
  installation of package ‘microbiomeMarker’ had non-zero exit status

Any suggestions/workaround?
Thanks in advance for any help and consideration!

kind regards
Martin

**Comment by yiluheihei** [comment]
Thanks for your interested in **microbiomeMarker**. It is an issue on package **RcppGSL**.  

If your os is ubuntu, you can install the libgsl2-dev to fix this issue: `sudo apt install libgsl2-dev`. Hope this helps you.

**Comment by mawa86** [comment]
Hi and thank you so much for getting back to me so quickly!

So i tried that, and I got the error 
>E: Unable to locate package libgsl2-dev

I had a quick look and I found 2 similar (but not exactly matching) packages on [packages.ubuntu.com](url) for ubuntu 18.04:

libgsl-dev ([https://packages.ubuntu.com/bionic/libgsl-dev](url))

and

libgsl23 ([https://packages.ubuntu.com/bionic/libgsl23](url))

which one should I go for?
Thanks again for both compiling MicrobiomeMarker and getting back to me!

Martin

**Comment by yiluheihei** [comment]
@mawa86 Sorry I am not familiar with  RcppGSL. Maybe you can try `libgsl-dev`.

**Comment by mawa86** [comment]
it was a **gsl** problem, I had to remove it from the system and re-download it from scratch.
This [answer on stackoverflow](https://stackoverflow.com/questions/69583193/installing-r-gsl-package-on-ubuntu) was really helpful.

Thank you too for your time
