### ISSUE TITLE
Cant load data("spontaneous_colitis")

### ISSUE THREAD

**Issue by dikiprawisuda** [yiluheihei/microbiomeMarker#8]
Hi, I can's seem to load data("spontaneous_colitis") in my script. I need to know the data format to be inserted.

Thank you.

**Comment by yiluheihei** [comment]
Sorry for the delayed reply. I'm on vacation and I will be free to solve this problem next week. :smile:

**Comment by dikiprawisuda** [comment]
No problem. Please enjoy your weekend :grin: :relaxed:

**Comment by yiluheihei** [comment]
I can load the data using `data("spontaneous_colitis")` in my computer.  Can you provide a reproducible example. https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

**Comment by dikiprawisuda** [comment]
Hi! I have tried to reinstall the package again and same result returned.
Here is the reprex. Let me know if I got it wrong.

![image](https://user-images.githubusercontent.com/55866525/92429653-8e86a580-f1cd-11ea-9998-c3b2e0f51e0a.png)
library(microbiomeMarker)
#> Registered S3 method overwritten by 'treeio':
#>   method     from
#>   root.phylo ape
#> Registered S3 method overwritten by 'treeio':
#>   method     from
#>   root.phylo ape
library(ggplot2)

# sample data from lefse python script. The dataset contains 30 abundance 
# profiles (obtained processing the 16S reads with RDP) belonging to 10 rag2 
# (control) and 20 truc (case) mice
data("spontaneous_colitis")
#> Warning in data("spontaneous_colitis"): data set 'spontaneous_colitis' not found

**Comment by yiluheihei** [comment]
Oh! I accidentally add the `^data$` to the `.buildignore`, and it was fixed right now.  The datasets in **microbiomeMarker** was lazily loaded which means  that they won’t occupy any memory until you use them. Thus, you can use the dataset directly after library the package without loading the data using `data("spontaneous_colitis")`.

Thanks for your feedback.
